### PR TITLE
Bootstrapping fixup

### LINKED ISSUE #129: Example fails on Lattigo branch
Example 3 fails on the lattigo branch. The problem is apparently related to the magnitude of the plaintext, (it can be fixed by setting `plaintext_inf_norm` to 2), but this isn't a problem with SEAL.

### LINKED ISSUE #163: Rethink ScaleEstimator with Bootstrapping
1. It's not clear that `DebugEval` needs a `ScaleEstimator` instance at all. Can it be removed completely?
2. `ScaleEstimator` might not make sense when bootstrapping is used. In particular, we should carefully think about what it means to be at a low ciphertext level mid-circuit, since `ScaleEstimator` uses plaintext norm in combination with ciphertext level to determine the estimated scale.

### PR DESCRIPTION
**Pull request by crockeea**
*Issue #, if available:*

*Description of changes:*
After using this branch to build a large-scale application, I've found several problems with the current approach to how evaluators handle bootstrapping. This PR fixes many issues and makes several simplifications including:
- Fixes #129 and re-enables examples for CI on this branch
- Complete refactor of `DepthFinder` evaluator. In particular:
   - Base depth calculation off of a new ciphertext metadata value rather than its HE level. This is because the HE level is doesn't help us compute circuit depth when bootstrapping is used. This results in a _much_ simpler depth computation, which leads to the second change:
    - Recombine `ImplicitDepthFinder` and `ExplicitDepthFinder` into a single `DepthFinder` evaluator. These had previously been split due to the complicated logic in each case. There's now identical logic in both cases, and that logic is much simpler.
    - Semantic result of the evaluator changed: previously, it was intended to help find the number of post-bootstrapping levels needed. Now this is provided as an argument, and the evaluator computes the total circuit depth (less any bootstrapping levels). The previous behavior could be useful, but it's extremely complicated, perhaps to the point of being meaningless, and that value isn't what the `DepthFinder` evaluator was intended to compute.
    - This requires that the user pass in the post-bootstrapping ciphertext level when a circuit uses bootstrapping. No change is needed for circuits that don't use bootstrapping.
- Change semantics of the `HEContext` and `CKKSParams` `max_ct_level()` API so that it returns the post-bootstrapping ciphertext level rather than the maximum parameter level. When parameters support bootstrapping, the maximum ciphertext level supported by the parameters is much larger than the post-bootstrapping level due to the levels consumed by bootstrapping itself. I previously thought it could be useful to utilize these levels before bootstrapping the first time, but the situation is very complicated because primes for bootstrapping levels don't necessarily have the same bit size as the "evaluation" primes. It's not clear how a user could take advantage of these levels, and it greatly complicates logic throughout HIT, so I made this simplifying assumption. I also added a `max_param_level()` API for the few cases where I actually care about that (e.g., when computing key sizes).
- The evaluators are designed so that `CKKSEvaluator` handles ciphertext metadata, while the evaluators only the unique computation required by that evaluator. When I first introduced bootstrapping, I broke that invariant, but it turned out to introduce more complexity than it solved. Now that evaluators require a "post-bootstrapping level" parameter to use bootstrapping, `CKKSEvaluator` can handle all of the metadata changes for bootstrapping, which simplifies several evaluators.
- Partially resolved #163: `DebugEval` _does_ need the `ScaleEstimator` evaluator (or at least `PlaintextEval`), and although I haven't put too much thought into it yet, `ScaleEstimator` nominally seems to do the Right Thing when bootstrapping is used.
- Moved the default ciphertext scale parameter to `CKKSEvaluator` and made each evaluator the ciphertext scale explicitly. This allows the parameter to be in a single place.
- A new `CKKSCiphertext` constructor that simplifies ciphertext initialization.
- Check that ciphertext input is initialized in all `CKKSEvaluator` APIs.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: src/hit/api/evaluator/opcount.cpp [hunk 1]
```diff
@@ -13,7 +13,9 @@ using namespace std;
 
 namespace hit {
 
-    OpCount::OpCount(int num_slots) : num_slots_(num_slots) {
+    OpCount::OpCount(int num_slots, int post_btp_lvl) : num_slots_(num_slots) {
+        post_boostrapping_level = post_btp_lvl;
+        post_bootstrapping_scale = pow(2, default_scale_bits);
```
Comment (SalusaSecondus) [inline src/hit/api/evaluator/opcount.cpp:18]: Why aren't these in the initializer?

File: src/hit/api/evaluator/rotations.cpp [hunk 2]
```diff
@@ -13,7 +13,9 @@ using namespace std;
 
 namespace hit {
 
-    RotationSet::RotationSet(int num_slots) : num_slots_(num_slots) {
+    RotationSet::RotationSet(int num_slots, int post_btp_lvl) : num_slots_(num_slots) {
+        post_boostrapping_level = post_btp_lvl;
+        post_bootstrapping_scale = pow(2, default_scale_bits);
```
Comment (SalusaSecondus) [inline src/hit/api/evaluator/rotations.cpp:18]: Why aren't these in the initializer?

File: src/hit/api/params.cpp [hunk 3]
```diff
@@ -52,6 +52,16 @@ namespace hit {
     }
 
     int CKKSParams::max_ct_level() const {
+        int maxLvl;
+        if (btp_params.has_value()) {
+            maxLvl = static_cast<int>(latticpp::maxLevel(lattigo_params)) - btp_params.value().bootstrapping_depth();
+        } else {
+            maxLvl = latticpp::maxLevel(lattigo_params);
+        }
```
Comment (SalusaSecondus) [inline src/hit/api/params.cpp:60]: NitPick:

I'd probably write it like this:
```suggestion
        int maxLvl = latticpp::maxLevel(lattigo_params);
        if (btp_params.has_value()) {
            maxLvl -= btp_params.value().bootstrapping_depth();
        }
```

**Review by SalusaSecondus — APPROVED** [review]
Approving under the assumption that all of my clarifying questions have simple answers.

File: examples/example_4_linearalgebra.cpp [hunk 4]
```diff
@@ -22,10 +22,12 @@ void example_4_driver() {
...
 	// Usually, we would use the RotationSet evaluator to compute the rotations we need.
-	// In this annotated example, it's easier to explicitly enumerate the rotations.
+	// However, we can only do "generic" (as opposed to evaluator-specific, e.g., decrypt)
+	// operations when using the RotationSet evaluator. In this annotated example, it's
+	// easier to just generate keys for all possible rotations rather than getting the
+	// exact subset.
 	vector<int> rotations;
-	rotations.push_back(num_slots/2);
-	for (int i = 1; i < num_slots / 2; i <<= 1) {
+	for (int i = 1; i <= num_slots / 2; i++) {
```
[the remark this answers is not in the document]
Comment (crockeea) [reply examples/example_4_linearalgebra.cpp:30]: In theory, the backend library would remove duplicates. In the worst case, this generates two keys for this shift, but it shouldn't matter.

File: src/hit/api/ciphertext.h [hunk 5]
```diff
@@ -147,7 +147,7 @@ namespace hit {
         latticpp::Ciphertext backend_ct;
 
         // `scale` is used by the ScaleEstimator evaluator
-        double scale_ = pow(2, 30);
+        double scale_;
```
[the remark this answers is not in the document]
Comment (crockeea) [reply src/hit/api/ciphertext.h:152]: In theory, this was ensured by carefully checking the `encrypt` procedure for each evaluator. However, it's easier to enforce with an explicit `CKKSCiphertext` constructor, so I've created one. Note, however, that we still need the empty constructor, e.g, for this snippet from my `LinearAlgebra` code:
```
CKKSCiphertext t2;
if (rotate_left) {
    t2 = eval.rotate_left(t1, i * stride);
} else {
    t2 = eval.rotate_right(t1, i * stride);
}
```
This is not a case where we want to assign to the first value and reassign to the second if the condition holds, because each assignment is expensive. But I'm using the new constructor in all `encrypt` definitions.

File: src/hit/api/evaluator/rotations.cpp (hunk 2 above)
Comment (crockeea) [reply src/hit/api/evaluator/rotations.cpp:18]: Seems to be a weird C++ism. I tried to put them in the initializer list, but it seems you can't initialize superclass members that way.

File: src/hit/api/evaluator/opcount.cpp (hunk 1 above)
Comment (crockeea) [reply src/hit/api/evaluator/opcount.cpp:18]: See below.
